### PR TITLE
Fusion360 files.

### PR DESCRIPTION
**Pull request by Wildtimo**
Reverse engineered the f360 parametric solid body mesh. And fixed the hole.

BEFORE:
image

HOLE:
image

AFTER:
image

NO HOLE:
image

### CODE REVIEW

**Comment by gorbit99** [comment]
Sorry, but I don't use fusion360, I use freecad, I wouldn't have any way to keep these up to date. I'll fix up the hole on my end and push the new changes.

**Comment by Wildtimo** [comment]
Ok, btw can you change the outer corner of the box so the wall is a consistent thickness all around? (2.7mm radius) this:
image

**Comment by gorbit99** [comment]
> Ok, btw can you change the outer corner of the box so the wall is a consistent thickness all around? (2.7mm radius)

That was an intended feature. The inner wall is kind of limited by the battery, but the outer wall can be much rounder this way. What issues are there with it?

**Comment by Wildtimo** [comment]
I guess it's just preference. It's an extra .6mm, I'll stop bugging you now XD.

**Pull request closed without merging**
